import os

SEED = 414
NUM_CPUS = 4
NUM_GPUS = 1
NUM_CLASS = 3
BATCH_SIZE = 10
DATA_PATH = os.path.join(os.getcwd(), 'data')
TEST_DATA_PATH = os.path.join(os.getcwd(), 'test_data')
ALL_DATA_LEN = 1300
TEST_DATA_LEN = 100
TRAIN_DATA_LEN = ALL_DATA_LEN - TEST_DATA_LEN
LEARNING_RATE = 3e-4
MOMENTUM = 0.9
WEIGHT_DECAY = 0.0001
EPOCHS = 5
NUM_WORKERS = 4
NUM_SAMPLES = 10
PROJECT_PATH = os.getcwd()